// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT8d0kN_hxnxICmOMeusxY2bZgMsnH5kY',
    appId: '1:696840604322:android:ec26e5dd4433a427d565fb',
    messagingSenderId: '696840604322',
    projectId: 'athlos-84089',
    storageBucket: 'athlos-84089.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8AQBrcvV9q-UG66p2DyUNmRmY423Jbuk',
    appId: '1:696840604322:ios:78b3c355c3ac5af9d565fb',
    messagingSenderId: '696840604322',
    projectId: 'athlos-84089',
    storageBucket: 'athlos-84089.firebasestorage.app',
    iosBundleId: 'com.pabloandres.athlos.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZJky27pnVEdFfkQTmwSn_yDGsvMXyPlg',
    appId: '1:696840604322:web:65d686d7a0d91619d565fb',
    messagingSenderId: '696840604322',
    projectId: 'athlos-84089',
    authDomain: 'athlos-84089.firebaseapp.com',
    storageBucket: 'athlos-84089.firebasestorage.app',
    measurementId: 'G-7PX3PQR24J',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8AQBrcvV9q-UG66p2DyUNmRmY423Jbuk',
    appId: '1:696840604322:ios:78b3c355c3ac5af9d565fb',
    messagingSenderId: '696840604322',
    projectId: 'athlos-84089',
    storageBucket: 'athlos-84089.firebasestorage.app',
    iosBundleId: 'com.pabloandres.athlos.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZJky27pnVEdFfkQTmwSn_yDGsvMXyPlg',
    appId: '1:696840604322:web:5ae46f91271090e4d565fb',
    messagingSenderId: '696840604322',
    projectId: 'athlos-84089',
    authDomain: 'athlos-84089.firebaseapp.com',
    storageBucket: 'athlos-84089.firebasestorage.app',
    measurementId: 'G-02RG2BQBK8',
  );

}